# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

dependents:
  - "template-*" # include

additional:
  - "template-*"

files:
  #  files to exclude
  - "!.github/workflows"
  - "!README.md"
  - "!.gitignore"
  - "!**/dependabot.yml"
  - "!**/template-sync.yml"
  #  files to sync
  - .github/template/_pull-request-target.yml: .github/workflows/pull-request-target.yml
  - .github/template/dependabot.yml: .github/dependabot.yml
  - "LICENSE"
