# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

additional:
  # temporarily include repos manually # https://github.com/github/docs/issues/3630
  - "template-*"

files:
  #  files to sync to other templates
  - "!.github/workflows"
  - "!README.md"
  - "!.gitignore"
  - "!**/dependabot.yml"
  - "!**/template-sync.yml"
