# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

additional:
  - "template-*"

files:
  #  files to exclude
  - "!.github/workflows/*"
  - "!.github/template/*"
  - "!**/template-sync.yml"
  - "!.gitignore"
  - "!README.*"
  #  files to sync
  - "LICENSE"
  - ".env.example"
