# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

name: pull-request-target

on:
  workflow_call:
    secrets:
      TOKEN_GITHUB:
        description: GitHub Personal Access Token
        required: true

# Concurrency settings ensure only one job runs at a time for a specific combination of Git ref and workflow.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  auto-merge:
    # only run for dependabot PRs
    if: github.actor == 'dependabot[bot]'
    uses: mmraisi/template-template/.github/template/_auto-merge.yml@main
    secrets: inherit

  metadata:
    uses: mmraisi/template-template/.github/template/_metadata.yml@main

  template-sync:
    needs:
      - metadata
    # only run for template repos
    if: needs.metadata.outputs.repository_is_template == 'true'
    uses: mmraisi/template-template/.github/template/_template-sync.yml@main
    secrets: inherit
    with:
      default_branch: ${{ needs.metadata.outputs.repository_default_branch }}
