# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #


name: auto-merge

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-dependabot:
    name: dependabot
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.3

      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          target: minor
          github-token: ${{ secrets.GH_TOKEN_WRITE }}
