# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

name: pull_request_target

on: pull_request_target

permissions: read-all

jobs:
  main:
    uses: mmraisi/template-template/.github/template/_pull-request-target.yml@main
    secrets: inherit
