# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

jobs:
  main:
    uses: mmraisi/template-template/.github/template/_push.yml@main
    secrets: inherit
    permissions:
      contents: write
      statuses: write
      pull-requests: write
