# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

name: template sync

on: [push, pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  template-sync:
    name: sync template
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: ahmadnassri/action-template-repository-sync@v2
        with:
          github-token: ${{ secrets.GH_TOKEN_WRITE }}
